name: "CI: Rust"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-build:
    name: "Rust: Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust
        uses: ./.github/actions/rust
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: just build

  rust-lint-code:
    name: "Rust: Lint Code"
    runs-on: ubuntu-latest
    needs:
      - rust-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust
        uses: ./.github/actions/rust
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint Code
        run: just lint-code

  rust-lint-format:
    name: "Rust: Lint Format"
    runs-on: ubuntu-latest
    needs:
      - rust-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust
        uses: ./.github/actions/rust
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint Format
        run: just lint-format

  rust-test:
    name: "Rust: Test"
    runs-on: ubuntu-latest
    needs:
      - rust-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust
        uses: ./.github/actions/rust
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: just test
