[package]
name = "chaos-symphony-network"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "^5"
quinn = "^0.10"
rcgen = "^0.11"
rustls = "^0.21"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"

[dev-dependencies]
tokio = { version = "^1", features = ["full"] }
